### ISSUE TITLE
A vs B

### ISSUE THREAD

**Issue by ameicler** [TUM-ML-Lab18/FaceSwap#1]
Hi,

I successfully preprocessed and launched PCGAN training but I feel like I am missing something.
 
If all data is uploaded into `raw` folder, how does the model learn who is the person A versus the person B? Shouldn't we distinguish the images?

Also:
- is there any preview of the model swaps saved quality during the training (in order to babysit the process)?
- what are final steps in order to convert a video once the model is properly trained?

Thanks for your great work!

**Comment by alebeck** [comment]
Hi,

for the DeepFakes Model, you should be able to put the images in `raw/A` and `raw/B`, respectively. This was not very clear from the README, I admit. Regarding your other questions:

- preview images should be logged as part of the validation step.
- take a look at `implementation/convert.py`. You could also use `ffmpeg` to convert your images back to a video file.

I hope I could help!
